project:
  type: book
book:
  title: "Sesiones Trabajo de Grado"
  author: "José M."
  date: "10/7/2025"
  chapters:
    - index.qmd
    - introduccion.qmd
    - micro.qmd
    - macro.qmd
    - summary.qmd
    - references.qmd
  


bibliography: references.bib
lang: es

crossref:
    chapters: true # 

format:
  html:
    theme: cosmo
    cover-image: img/portada.png
  pdf:
    latex_engine: pdflatex  # O lualatex
    # mainfont: Times New Roman
    documentclass: scrreprt
    include-in-header: latex/preamble.tex
    include-before-body: latex/portada.tex
    csl: apa.csl
    fontsize: 12pt
    geometry: left=2.54cm, right=2.54cm, top=2.54cm, bottom=2.54cm
    biblio-style: apa
    toc: true           # Activa el Índice de Contenido (Table of Contents)
    lof: true
    lot: true
    toc-title: "Índice"
    lof-title: "Índice de Figuras"
    lot-title: "Índice de Tablas"

editor: visual

