project:
  type: book
book:
  title: "Sesiones Trabajo de Grado"
  author: "Jos√© M."
  date: "10/7/2025"
  chapters:
    - index.qmd
    - introduccion.qmd
    - micro.qmd
    - macro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: es

format:
  html:
    theme: cosmo
    cover-image: img/portada.png
  pdf:
    latex_engine: pdflatex  # O lualatex
    # mainfont: Times New Roman
    documentclass: scrreprt
    include-in-header: latex/preamble.tex
    include-before-body: latex/portada.tex
    csl: apa.csl
    fontsize: 12pt
    geometry: left=2.54cm, right=2.54cm, top=2.54cm, bottom=2.54cm
    biblio-style: apa
editor: visual

