project:
  type: book

book:
  title: "Sesiones Trabajo de Grado"
  author: "Jos√©"
  date: "10/7/2025"
  chapters:
    - index.qmd
    - summary.qmd
    - introduccion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: img/portada.png
  pdf:
    documentclass: scrreprt
    include-in-header: latex/preamble.tex
    include-before-body: latex/portada.tex
    csl: apa.csl
    biblio-style: apa
    fontsize: 12pt
    geometry: left=2.54cm, right=2.54cm, top=2.54cm, bottom=2.54cm
    mainfont: Times New Roman



editor: visual

